config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  namespace :api do
    namespace :v1 do
      resources :monsters
      resources :teams
    end
  end

  root 'home#index'
  resources :monsters
  resources :teams

end

app/models/monster.rb
class Monster < ActiveRecord::Base
  belongs_to :user
  belongs_to :team
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :monsters
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  has_many :monsters
  has_many :teams
  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update
  validates_uniqueness_of :email, scope: :provider

  def self.from_omniauth(auth)
    email = auth.info.email
    where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
      user.email = email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com"
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end
end

app/controllers/api/v1/monsters_controller.rb
module Api
  module V1
    class MonstersController < ApplicationController
      skip_before_filter :verify_authenticity_token
      respond_to :json

      def index
        respond_with Monster.all
      end

      def show
        monstor =  Monster.find(params[:id])
        render(json: monstor)
      end

      def create
        respond_with Monster.create(monster_params)
      end

      def update
        respond_with Monster.update(params[:id], params[:monsters])
      end

      def destroy
        respond_with Monster.destroy(params[:id])
      end

      private
      def monster_params
        params.require(:monster).permit(:name, :type, :power, :user_id, :team_id)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :signedin_page
  before_filter :monster_create_restriction
  before_filter :team_create_restriction

  def signedin_page
    if user_signed_in? && request.path == '/'
      redirect_to monsters_path
    end
  end

  def monster_create_restriction
    if user_signed_in? && request.path == new_monster_path && current_user.monsters.count >= 20
      redirect_to monsters_path
    end
  end

  def team_create_restriction
    if user_signed_in? && request.path == new_team_path && current_user.teams.count >= 3
      redirect_to monsters_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :set_monster, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: :create

  # GET /monsters
  # GET /monsters.json
  def index
    @monsters = current_user.monsters
    @count = 20 - current_user.monsters.count
    @teams = current_user.teams
    @teams_count = 3 - @teams.count
  end

  # GET /monsters/1
  # GET /monsters/1.json
  def show
  end

  # GET /monsters/new
  def new
    @monster = Monster.new
  end

  # GET /monsters/1/edit
  def edit
  end

  # POST /monsters
  # POST /monsters.json
  def create
    @monster = current_user.monsters.new(monster_params)

    respond_to do |format|
      if @monster.save
        format.html { redirect_to @monster, notice: 'Monster was successfully created.' }
        format.json { render :show, status: :created, location: @monster }
      else
        format.html { render :new }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monsters/1
  # PATCH/PUT /monsters/1.json
  def update
    respond_to do |format|
      if @monster.update(monster_params)
        format.html { redirect_to @monster, notice: 'Monster was successfully updated.' }
        format.json { render :show, status: :ok, location: @monster }
      else
        format.html { render :edit }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monsters/1
  # DELETE /monsters/1.json
  def destroy
    @monster.destroy
    respond_to do |format|
      format.html { redirect_to monsters_url, notice: 'Monster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monster
      @monster = Monster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def monster_params
      params.require(:monster).permit(:name, :monster_type, :power)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_filter :authenticate_user!, only: :new

  def new
    @team = Team.new
    @monsters = current_user.monsters.where('team_id IS NULL')
  end

  def create
    @team = current_user.teams.create(team_params)
    params[:monsters].each do |monster_id|
      @monster = Monster.find(monster_id)
      @monster.update(team_id: @team.id)
    end
    redirect_to monsters_path
  end

  private
    def team_params
      params.require(:team).permit(:name, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>Rubymon</h1>
  <p>Catch, collect, and battle monstors.</p>
  <p>
    <a class="btn btn-primary btn-large" href="/users/auth/facebook">
      Login in with Facebook
    </a>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubymon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<style type="text/css">
    body{
        padding-top: 60px;
    }
</style>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Rubymon', root_path, class: 'navbar-brand' %>
    </div>
    <% if user_signed_in? %>
      <li class="navbar-brand pull-right"><%= current_user.name %></li>
      <li><%= link_to('Logout', destroy_user_session_path, :method => :delete, class: "navbar-brand pull-right") %></li>
    <% end %>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/monsters/_form.html.erb
<%= form_for(@monster) do |f| %>
  <% if @monster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monster.errors.count, "error") %> prohibited this monster from being saved:</h2>

      <ul>
      <% @monster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-md-8">
    <%= f.text_field :name, placeholder: 'Name', class: 'form-control' %>
  </div><br />

  <div class="form-group col-md-8">
    <%= f.text_field :power, placeholder: 'Power', class: 'form-control' %>
  </div><br />

  <div class="form-group col-md-8">
    <%= f.select :monster_type, [['Fire','fire'],['Water','water'],['Earth','earth'], ['Electric', 'electric'], ['Wind', 'wind']] %>
  </div><br />

  <div class="form-group col-md-8">
    <%= f.submit %>
  </div>
<% end %>

app/views/monsters/edit.html.erb
<h1>Editing Monster</h1>

<%= render 'form' %>

<%= link_to 'Show', @monster %> |
<%= link_to 'Back', monsters_path %>

app/views/monsters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Monsters</h1>

<%= @teams_count %> teams remaining
<br />
<%= link_to button_tag('Create a team', class: 'btn btn-default'), new_team_path unless current_user.teams.count >= 3 %>
<br /><br />

<% if @teams.any? %>
  <% for team in @teams %>
    <div class="well">
      <p><%= team.name %></p>
      <% team.monsters.each do |monster| %>
        <li><%= monster.name %></li>
      <% end %>
    </div>
  <% end %>
<% end %>

<%= @count %> monsters remaining
<br /><br />

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @monsters.each do |monster| %>
      <tr>
        <td><%= monster.name %></td>
        <td><%= link_to 'Show', monster %></td>
        <td><%= link_to 'Edit', edit_monster_path(monster) %></td>
        <td><%= link_to 'Destroy', monster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Monster', new_monster_path unless current_user.monsters.count >= 20 %>

app/views/monsters/new.html.erb
<h1>New Monster</h1>

<%= render 'form' %>

app/views/monsters/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_monster_path(@monster) %> |
<%= link_to 'Back', monsters_path %>